// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_5aCFoCSl78YTaDZCC4K2ZbxZmdzotg',
    appId: '1:792049532387:web:9024be10e336993a0674d6',
    messagingSenderId: '792049532387',
    projectId: 'notifyju-dc3fd',
    authDomain: 'notifyju-dc3fd.firebaseapp.com',
    databaseURL: 'https://notifyju-dc3fd-default-rtdb.firebaseio.com',
    storageBucket: 'notifyju-dc3fd.appspot.com',
    measurementId: 'G-GFF93D80F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFca4Y3-Lpk3VGQ4_qhP6tx5lD0v39NWc',
    appId: '1:792049532387:android:c2af63fc0ca977e90674d6',
    messagingSenderId: '792049532387',
    projectId: 'notifyju-dc3fd',
    databaseURL: 'https://notifyju-dc3fd-default-rtdb.firebaseio.com',
    storageBucket: 'notifyju-dc3fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOJag0mGqMRF5eptdF-DXHs0YLH4qRuQ',
    appId: '1:792049532387:ios:6145eaf5df91f9370674d6',
    messagingSenderId: '792049532387',
    projectId: 'notifyju-dc3fd',
    databaseURL: 'https://notifyju-dc3fd-default-rtdb.firebaseio.com',
    storageBucket: 'notifyju-dc3fd.appspot.com',
    iosBundleId: 'com.example.notifyJu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzOJag0mGqMRF5eptdF-DXHs0YLH4qRuQ',
    appId: '1:792049532387:ios:6145eaf5df91f9370674d6',
    messagingSenderId: '792049532387',
    projectId: 'notifyju-dc3fd',
    databaseURL: 'https://notifyju-dc3fd-default-rtdb.firebaseio.com',
    storageBucket: 'notifyju-dc3fd.appspot.com',
    iosBundleId: 'com.example.notifyJu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY_5aCFoCSl78YTaDZCC4K2ZbxZmdzotg',
    appId: '1:792049532387:web:7b16210777f05db10674d6',
    messagingSenderId: '792049532387',
    projectId: 'notifyju-dc3fd',
    authDomain: 'notifyju-dc3fd.firebaseapp.com',
    databaseURL: 'https://notifyju-dc3fd-default-rtdb.firebaseio.com',
    storageBucket: 'notifyju-dc3fd.appspot.com',
    measurementId: 'G-0YGH7QTGBR',
  );
}
