// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL19rfM_alP64pMgPZtHu9atbBhAuW9B4',
    appId: '1:921146051559:web:81e8fe8bd20bad586a0b42',
    messagingSenderId: '921146051559',
    projectId: 'notify-ju',
    authDomain: 'notify-ju.firebaseapp.com',
    storageBucket: 'notify-ju.appspot.com',
    measurementId: 'G-X4KFLZ9MS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43IUGObCFYO-_P1iig1FxMPGvSJfdAAs',
    appId: '1:921146051559:android:8c8ea31d65a4fe526a0b42',
    messagingSenderId: '921146051559',
    projectId: 'notify-ju',
    storageBucket: 'notify-ju.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7j6el3fmPkrzoKF3VsSzlgUZmbZpvWt8',
    appId: '1:921146051559:ios:3c92b2f3da616a8d6a0b42',
    messagingSenderId: '921146051559',
    projectId: 'notify-ju',
    storageBucket: 'notify-ju.appspot.com',
    iosBundleId: 'com.example.notifyJu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7j6el3fmPkrzoKF3VsSzlgUZmbZpvWt8',
    appId: '1:921146051559:ios:f6d8e3446573be6c6a0b42',
    messagingSenderId: '921146051559',
    projectId: 'notify-ju',
    storageBucket: 'notify-ju.appspot.com',
    iosBundleId: 'com.example.notifyJu.RunnerTests',
  );
}
